/** Generated by scripts/build-adult-rules.mjs. */
export const ADULT_RULESETS = [{"id":"adult_01","count":25972},{"id":"adult_02","count":25972},{"id":"adult_03","count":25972},{"id":"adult_04","count":25972},{"id":"adult_05","count":25971},{"id":"adult_06","count":25971}] as const;
export const ADULT_DOMAIN_COUNT = 155830;
